---
title: "HORIZONTES AMPLIADOS"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---


```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

<div style="text-align: justify">

# Nosso Mural Virtual

Bem-vindo ao Mural Virtual "Horizontes Ampliados"! Esta é uma iniciativa da 
coordenação de curso da Universidade Federal de Itajubá, dedicada à ampliação 
dos horizontes intelectuais e culturais dos nossos estudantes e comunidade 
acadêmica. Em nosso mural, você encontrará uma variedade de conteúdos, desde 
artigos de opinião provocativos até análises culturais inspiradoras e gráficos 
informativos. Estamos comprometidos em fomentar o debate saudável, a reflexão 
crítica e a busca pelo conhecimento em todas as suas formas. Esteja pronto para 
explorar novas ideias, desafiar conceitos estabelecidos e expandir seus 
horizontes junto conosco. Seja bem-vindo ao "Horizontes Ampliados" - onde a 
jornada do conhecimento nunca tem fim.

# Perspectivas em Debate

## A Roda Gira, Excelência

No mural nosso mural de março, o artigo "A Roda Gira, Excelência" do autor 
Professor Dagoberto Alves de Almeida reflete sobre a dualidade do conhecimento 
como uma ferramenta poderosa, destacando a importância das questões éticas 
relacionadas ao seu uso e argumentando que a ciência não é apolítica, citando 
exemplos históricos como o negacionismo científico durante a pandemia e 
perseguições a cientistas como Galileo Galilei. O autor critica a interferência 
política na ciência, como o caso específico da intervenção do governo de Minas 
Gerais na Fundação de Amparo à Ciência de Minas Gerais (Fapemig), defendendo a 
necessidade de proteger a autonomia das instituições científicas e ressaltando 
o papel fundamental da Fapemig no financiamento de pesquisas científicas em 
Minas Gerais. Ele conclui enfatizando a importância da liberdade científica e 
da manutenção de um estatuto que proteja a ciência de interferências políticas, 
destacando que a verdade científica não deve ser subjugada a agendas políticas 
temporárias.

- Leia o Artigo na Íntegra: [**https://diariodopoder.com.br/opiniao/a-roda-gira-excelencia**](https://diariodopoder.com.br/opiniao/a-roda-gira-excelencia)

**SOBRE O AUTOR:**

- DAGOBERTO ALVES DE ALMEIDA

  - Engenheiro Mecânico de Produção pela EFEI – 1982

  - Mestre em Engenharia de Produção pela COPPE-UFRJ - 1986

  - PhD in Manufacturing System Engineering – University of Cranfield – UK

  - Professor Titular em Gestão da Produção 

  - Reitor (eleito e indicado) da Universidade Federal de Itajubá (UNIFEI) nos mandatos 2013/16 e     2017/18

  - ID Lattes: 6443290239075662


# Mapeando Realidades

# Arte e Contexto